import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        secondaryBg: "var(--secondaryBg)",
        surface: "var(--surface)",
        elevatedSurface: "var(--elevatedSurface)",
        primaryText: "var(--primaryText)",
        secondaryText: "var(--secondaryText)",
        mutedText: "var(--mutedText)",
        border: "var(--border)",
        primaryAccent: "var(--primaryAccent)",
        primaryHover: "var(--primaryHover)",
        success: "#10B981",
        warning: "#F59E0B",
        error: "#EF4444",
        champagne: "#F9F6F0",
        champagneDark: "#EADEC9",
        champagneGold: "#B59E7C",
        champagneHover: "#A18A6A",

        // Stitch MD3 custom colors
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        "secondary": "#0051d5",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#7c839b",
        "outline-variant": "#c6c6cd",
        "on-tertiary-fixed": "#2a1700",
        "primary-fixed": "#dae2fd",
        "on-surface": "#191c1e",
        "on-surface-variant": "#45464d",
        "surface-tint": "#565e74",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary": "#000000",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#bec6e0",
        "tertiary-fixed": "#ffddb8",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#bec6e0",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-container": "#eceef0",
        "tertiary-container": "#2a1700",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed-variant": "#003ea8",
        "surface-bright": "#f7f9fb",
        "secondary-fixed-dim": "#b4c5ff",
        "tertiary-fixed-dim": "#ffb95f",
        "secondary-fixed": "#dbe1ff",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#00174b",
        "on-error-container": "#93000a",
        "primary": "#000000",
        "primary-container": "#131b2e",
        "secondary-container": "#316bf3",
        "surface-container-highest": "#e0e3e5",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#fefcff",
        "on-primary-fixed": "#131b2e",
        "inverse-on-surface": "#eff1f3",
        "outline": "#76777d",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "sans-serif"],
        script: ["var(--font-script)", "cursive"],
        
        // Stitch custom typography config classes mapping
        "body-md": ["Geist", "sans-serif"],
        "label-caps": ["'JetBrains Mono'", "monospace"],
        "headline-md": ["Chivo", "sans-serif"],
        "headline-lg": ["Chivo", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "display-xl": ["Chivo", "sans-serif"],
        "headline-lg-mobile": ["Chivo", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"]
      },
      fontSize: {
        // Stitch font size & styles presets mapping
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }],
        "headline-md": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "32px", fontWeight: "400" }],
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["13px", { lineHeight: "18px", fontWeight: "500" }]
      },
      borderRadius: {
        btn: "16px",
        card: "16px",
        input: "14px",
        dialog: "16px",
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "margin-page": "64px",
        "asymmetric-offset": "80px",
        "section-gap": "128px",
        gutter: "32px",
      },
      transitionDuration: {
        normal: "200ms",
        slow: "300ms",
      },
      boxShadow: {
        subtle: "0 2px 8px rgba(0, 0, 0, 0.05)",
      }
    },
  },
  plugins: [],
};

export default config;
